### ISSUE TITLE
My God, why have you created this?

### ISSUE THREAD

**Issue by ghost** [Pizzacus/general-furry#1]

**Comment by Pizzacus** [comment]
<h1>
OwO <sup>OwO <sup>OwO</sup></sup></sup> <sup><sup>OwO</sup> OwO</sup> OwO<br>
<sup>OwO <sup>OwO</sup></sup> <sup><sup>OwO</sup> OwO</sup> OwO <sub>OwO</sub><br>
<sup><sup>OwO</sup></sup> <sup><sup>OwO</sup> OwO</sup> OwO <sub>OwO <sub>OwO</sub></sub><br>
<sup><sup>OwO</sup> OwO</sup> OwO <sub>OwO <sub>OwO</sub></sub> <sub><sub>OwO</sub></sub><br>
<sup>OwO</sup> OwO <sub>OwO <sub>OwO</sub></sub> <sub><sub>OwO</sub> OwO</sub><br>
OwO <sub>OwO <sub>OwO</sub></sub> <sub><sub>OwO</sub> OwO</sub> OwO<br>
<br>
ＴＨＩＳ 　ＭＵＳＴ 　ＢＥ <br>
ＴＨＥ 　ＷＯＲＫ 　ＯＦ <br>
ＡＮ 　ＥＮＥＭＹ <i>「ＢＵＬＧＥ」</i>！！<br>
<br>
OwO <sup>OwO <sup>OwO</sup></sup></sup> <sup><sup>OwO</sup> OwO</sup> OwO<br>
<sup>OwO <sup>OwO</sup></sup> <sup><sup>OwO</sup> OwO</sup> OwO <sub>OwO</sub><br>
<sup><sup>OwO</sup></sup> <sup><sup>OwO</sup> OwO</sup> OwO <sub>OwO <sub>OwO</sub></sub><br>
<sup><sup>OwO</sup> OwO</sup> OwO <sub>OwO <sub>OwO</sub></sub> <sub><sub>OwO</sub></sub><br>
<sup>OwO</sup> OwO <sub>OwO <sub>OwO</sub></sub> <sub><sub>OwO</sub> OwO</sub><br>
OwO <sub>OwO <sub>OwO</sub></sub> <sub><sub>OwO</sub> OwO</sub> OwO<br>
</h1>

**Comment by ghost** [comment]
Beautiful UwU
